src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="user")
 */
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @var int
     *@ORM\Column(name="id",type="integer")
     *@ORM\Id
     *@ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * * @ORM\Column(length=180, unique=true)
     * @Assert\NotBlank (message="Please enter your email!")
     * @Assert\Email (message="Invalid mail!")
     */
    private ?string $email = null;
    /**
     * @ORM\Column
     */
    private int $state =0 ;
    /**
     * @ORM\Column
     */
    private string $roles ;


    private string $role;
    /**
     * @var string The hashed password
     **
     * @Assert\NotBlank (message="Please enter your password!")
     * @Assert\Regex(
     *     pattern="/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{1,8}$/",
     *     message="The password should contain at least one uppercase letter, numbers, lowercase letters, and special characters, and be no longer than 8 characters"
     * )
     * @ORM\Column
     */
    private ?string $password = null;


    /**
     *
     *  @ORM\Column(length=255)
     * @Assert\NotBlank (message="Please enter Firstname!")
     * @Assert\Regex(
     *     pattern="/^[a-zA-Z]+$/",
     *     message="Firstname should contain only alphabetical letters"
     * )
     */
    private ?string $prenom = null;


    /**
     * @ORM\Column(length=255)
     * @Assert\NotBlank (message="Please enter your Lastname!")
     * @Assert\Regex(
     *     pattern="/^[a-zA-Z]+$/",
     *     message="Lastname should contain only alphabetical letters"
     * )
     */
    private ?string $nom = null;


    /**
     * @ORM\Column(type=Types::DATE_MUTABLE)
     * @Assert\LessThanOrEqual("-18 years", message="You must be at least 18 years old.")
     * @Assert\NotBlank(message="Please enter your birth date")
     */
    private ?\DateTimeInterface $date_naissance = null;




    /**
     * @ORM\Column
     * @Assert\Regex(
     *     pattern="/^\d{8}$/",
     *     message="The phone number should be exactly 8 digits"
     * )
     * @Assert\NotBlank(message="Please enter your phone number")
     */
    private ?int $numTel = null;


    /**
     *@ORM\Column(length=255)
     *
     *@Assert\NotBlank(message="Please enter your adress")
     */
    private ?string $adresse = null;
    /**
     * @ORM\Column(nullable=true)
     */
    private ?float $latitude = null;

    /**
     * @ORM\Column(nullable=true)
     */
    private ?float $longitude = null;

    /**
     * @ORM\Column(type="boolean",nullable=true,name="is_verified")
     *
     */
    private $isVerified = false;
    /**
     *@ORM\Column(length=255)
     */
    private ?string $block = 'unBlocked';
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Evenement", mappedBy="user")
     */
    private Collection  $events;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Evenement", mappedBy="user")
     */
    private Collection $participations;

    public function __construct()
    {
        $this->participations = new ArrayCollection();
        $this->events = new ArrayCollection();

    }

    /**
     * @return Collection<int, Evenement>
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }
    /**
     * @return Collection<int, ParticipationEv>
     */

    public function getBlock(): ?string
    {
        return $this->block;
    }

    public function setBlock(string $block): self
    {
        $this->block = $block;

        return $this;
    }
    public function getId(): ?int
    {
        return $this->id;
    }
    public function getState(): ?int
    {
        return $this->state;
    }
    public function setState(int $state): self
    {
         $this->state=$state;
         return $this;
    }
    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): string
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER


        return $roles;
    }

    public function setRoles(string $roles): self
    {
        $this->roles = $roles;

        return $this;
    }
    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }
    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }


    public function getNumTel(): ?int
    {
        return $this->numTel;
    }

    public function setNumTel(int $numTel): self
    {
        $this->numTel = $numTel;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }
    /**
     * @return float|null
     */
    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    /**
     * @param float|null $latitude
     */
    public function setLatitude(?float $latitude): void
    {
        $this->latitude = $latitude;
    }

    /**
     * @return float|null
     */
    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    /**
     * @param float|null $longitude
     */
    public function setLongitude(?float $longitude): void
    {
        $this->longitude = $longitude;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
    public function addEvent(Evenement $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setUser($this);
        }

        return $this;
    }

    public function removeEvent(Evenement $event): self
    {
        if ($this->events->contains($event)) {
            $this->events->removeElement($event);
            // set the owning side to null (unless already changed)
            if ($event->getUser() === $this) {
                $event->setUser(null);
            }
        }

        return $this;
    }
    public function addParticipation(ParticipationEv $participation): self
    {
        if (!$this->participations->contains($participation)) {
            $this->participations[] = $participation;
            $participation->setUser($this);
        }

        return $this;
    }

    public function removeParticipation(ParticipationEv $participation): self
    {
        if ($this->participations->contains($participation)) {
            $this->participations->removeElement($participation);
            // set the owning side to null (unless already changed)
            if ($participation->getUser() === $this) {
                $participation->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
/*
Cette ligne définit une nouvelle classe UserType,
qui étend AbstractType et sert à définir un type de formulaire personnalisé pour l'entité User.
*/
class UserType extends AbstractType
{
/*
Ce code est une méthode appelée buildForm() de la classe "UserType" qui étend la classe AbstractType de Symfony.
Cette méthode permet de construire un formulaire pour l'entité "User".
*/ 

    public function buildForm(FormBuilderInterface $builder, array $options): void
//La méthode prend deux arguments: $builder et $options. 
//La méthode ajoute des champs au formulaire en utilisant la méthode add() du $builder.
    {
        $builder
            ->add('nom',TextType::class,['label'=>false,'attr'=>['placeholder'=>'Lastname','class'=>'form-control']])
            ->add('prenom',TextType::class,['label'=>false,'attr'=>['placeholder'=>'Firstname','class'=>'form-control']])
            ->add('date_naissance',DateType::class,[ 'placeholder' => [
                'Year' => 'Year', 'Month' => 'Month', 'Day' => 'Day'],'years' => range(date('Y') - 100, date('Y'))])
            ->add('numTel',TextType::class,['label'=>false,'attr'=>['placeholder'=>'Phone','class'=>'form-control']])
            //changement le type d'adresse de texte  a liste des roulants ("choice type")
            ->add('adresse',ChoiceType::class,[
                'choices'=>[
                    'Tunis'=>'Tunis',
                    'Sfax'=>'Sfax',
                    'Sousse'=>'Sousse',
                    'Kairouan'=>'Kairouan',
                    'Métouia'=>'Métouia',
                    'Kebili'=>'Kebili',
                    'Bizerte'=>'Bizerte',
                    'Sidi Bouzid'=>'Sidi Bouzid',
                    'Gabés'=>'Gabés',
                    'Ariana'=>'Ariana',
                    'Béja'=>'Béja',

                ]
            ])
            ->add('role', ChoiceType::class, [
                'choices' => [
                    'Freelancer' => 'Freelancer',
                    'Client' => 'client',
                ],
                'expanded' => true
            ])
            ->add('email',TextType::class,['label'=>false,'attr'=>['placeholder'=>'Email','class'=>'form-control']])

            ->add('password',PasswordType::class,['label'=>false,'attr'=>['placeholder'=>'Password','class'=>'form-control']])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <div class="text-center" style="  margin-top: 50px;">
        <button type="submit" class="btn btn-primary">Supprimer</button>

    </div>
</form>

templates/user/_form.html.twig
{% for flash_error in app.flashes('verify_email_error') %}
    <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
{% endfor %}
{{ form_start(form, {'attr': {'class': 'mt-4 pt-2','novalidate': 'novalidate'}}) }}
<div class="row pull-center">
    <div class="col-md-6">
        <div class="form-floating form-floating-custom mb-3">
            {{ form_row(form.prenom) }}
            <div class="form-floating-icon">
                <i class="uil uil-user"></i>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-floating form-floating-custom mb-3">
            {{ form_row(form.nom) }}
            <div class="form-floating-icon">
                <i class="uil uil-user"></i>
            </div>
        </div>
    </div>
</div>
<div class="form-floating form-floating-custom mb-3">
    {{ form_row(form.date_naissance) }}
    <div class="form-floating-icon">
        <i class="uil uil-envelope-alt"></i>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="form-floating form-floating-custom mb-3">
            {{ form_row(form.numTel) }}
            <div class="form-floating-icon">
                <i class="uil uil-user"></i>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-floating form-floating-custom mb-3">
            {{ form_row(form.adresse) }}
            <div class="form-floating-icon">
                <i class="uil uil-user"></i>
            </div>
        </div>
    </div>
</div>
<div class="form-floating form-floating-custom mb-3">
    {{ form_row(form.role) }}
    <div class="form-floating-icon">
        <i class="uil uil-envelope-alt"></i>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="form-floating form-floating-custom mb-3">
            {{ form_row(form.email) }}
            <div class="form-floating-icon">
                <i class="uil uil-user"></i>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-floating form-floating-custom mb-3">
            {{ form_row(form.password) }}
            <div class="form-floating-icon">
                <i class="uil uil-user"></i>
            </div>
        </div>
    </div>
</div>
<div class="mt-3">
    <button class="btn btn-primary w-100" type="submit">Signup</button>
</div>

<div class="mt-4 pt-3 text-center">
    <p class="text-muted mb-0">Already have an account ? <a href="{{path('app_login')}}" class="fw-semibold text-decoration-underline"> Login </a> </p>
</div>
{% if form_errors(form) %}
    <div class="error-message">
        {{ form_errors(form) }}
    </div>
{% endif %}
{{ form_end(form) }}

templates/user/_formeditadmin.html.twig
<div class="col-lg-6">

    <div class="card">
        <div class="card-body pull-center">
            <h5 class="card-title">Mon profil</h5>
            {{ form_start(form,{'attr': {'novalidate': 'novalidate'}}) }}
            <div class="col-12">
                <label for="inputNanme4" class="form-label"></label>
                {{ form_row(form.nom)}}
            </div>
            <div class="col-12">
                <label for="inputNanme4" class="form-label"></label>
                {{ form_row(form.prenom)}}
            </div>
            <div class="col-12">
                <label for="inputNanme4" class="form-label"></label>
                {{ form_row(form.date_naissance)}}
            </div>
            <div class="col-12">
                <label for="inputNanme4" class="form-label"></label>
                {{ form_row(form.numTel)}}
            </div>
            <div class="col-12">
                <label for="inputNanme4" class="form-label"></label>
                {{ form_row(form.adresse)}}
            </div>
            <div class="col-12">
                <label for="inputNanme4" class="form-label"></label>
                {{ form_row(form.email)}}
            </div>

            <div class="col-12">
                <label for="inputNanme4" class="form-label"></label>
                {{ form_row(form.password)}}
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Modifier</button>

            </div>

            {{ form_end(form) }}
        </div>
    </div>
</div>

templates/user/_formeditprofilefront.html.twig
{{ form_start(form,{'attr': {'novalidate': 'novalidate'}}) }}
<div class="form_row_box">
    <div class="form_row_box_body">
        <div class="form-row">
            <div class="col-lg-6 col-md-12">
                <div class="form-group">
                    {{ form_row(form.prenom) }}
                </div>
            </div>
            <div class="col-lg-6 col-md-12">
                <div class="form-group">
                    {{ form_row(form.nom) }}
                </div>
            </div>
            <div class="col-lg-6 col-md-12">
                <div class="form-group">
                    {{ form_row(form.date_naissance) }}
                </div>
            </div>
            <div class="col-lg-6 col-md-12">
                <div class="form-group">
                    {{ form_row(form.numTel) }}
                </div>
            </div>
            <div class="col-lg-6 col-md-12">
                <div class="form-group">
                    {{ form_row(form.adresse) }}
                </div>
            </div>
            <div class="col-lg-6 col-md-12">
                <div class="form-group">
                    {{ form_row(form.email) }}
                </div>
            </div>

            <div class="col-lg-6 col-md-12">
                <div class="form-group">
                    {{ form_row(form.password) }}
                </div>
            </div>
            <div class="col-lg-12 col-md-12">
                <div class="form-group">
                    <button type="submit" class="btn dark-3">Update profile</button>
                </div>
            </div>
        </div>
    </div>
</div>
{{ form_end(form) }}

templates/user/_formnew2.html.twig
<div class="col-lg-6">

    <div class="card">
        <div class="card-body pull-center">
            <h5 class="card-title">Ajouter un utilisateur</h5>
            {{ form_start(form,{'attr': {'novalidate': 'novalidate'}}) }}
            <div class="col-12">
                <label for="inputNanme4" class="form-label"></label>
                {{ form_row(form.nom)}}
            </div>
            <div class="col-12">
                <label for="inputNanme4" class="form-label"></label>
                {{ form_row(form.prenom)}}
            </div>
            <div class="col-12">
                <label for="inputNanme4" class="form-label"></label>
                {{ form_row(form.date_naissance)}}
            </div>
            <div class="col-12">
                <label for="inputNanme4" class="form-label"></label>
                {{ form_row(form.numTel)}}
            </div>
            <div class="col-12">
                <label for="inputNanme4" class="form-label"></label>
                {{ form_row(form.adresse)}}
            </div>
            <div class="col-12">
                <label for="inputNanme4" class="form-label"></label>
                {{ form_row(form.email)}}
            </div>
            <div class="col-12">
                <label for="inputNanme4" class="form-label"></label>
                {{ form_row(form.role)}}
            </div>

            <div class="col-12">
                <label for="inputNanme4" class="form-label"></label>
                {{ form_row(form.password)}}
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Modifier</button>

            </div>

            {{ form_end(form) }}
        </div>
    </div>
</div>

templates/user/edit.html.twig
{% extends 'baseBack.html.twig' %}

{% block tableForm %}


    {{ include('user/_formedit.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_user_index') }}">Retour</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/edit2.html.twig
{% extends 'baseFront2.html.twig' %}

{% block tableForm %}
    <h2>My profile<span class="theme-cl-2"></span></h2>

    {{ include('user/_formeditprofilefront.html.twig') }}

{% endblock %}

templates/user/editAdmin.html.twig
{% extends 'baseBack.html.twig' %}

{% block tableForm %}


    {{ include('user/_formeditadmin.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_user_index') }}">Retour</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/index.html.twig
{% extends 'baseBack.html.twig' %}

{% block tableForm %}
<div style=" justify-content: center; margin-left: 150px;">

    <div class="card">
        <div  style="display: flex;align-items: center;justify-content: center;margin-top: 20px; padding: 50px;">

            <div class="card-body">
                <center> <h1 class="card-title" >Liste des utilisateurs</h1> </center>



                <table class="table">
        <thead>
            <tr>

                <th>Prenom</th>
                <th>Nom</th>
                <th>Date_naissance</th>
                <th>Adresse</th>
                <th>actions</th>
                <th>Block/Unblock</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>

                <td>{{ user.prenom }}</td>
                <td>{{ user.nom }}</td>
                <td>{{ user.dateNaissance ? user.dateNaissance|date('Y-m-d') : '' }}</td>
                <td>{{ user.adresse }}</td>
                <td>
                    <button class="btn btn-primary" onclick="window.location.href='{{ path('app_user_show', {'id': user.id}) }}'">Détails</button>
                    <button class="btn btn-primary" onclick="window.location.href='{{ path('app_user_edit', {'id': user.id}) }}'">Modifier</button>

                </td>
                <td>
                    {% if user.block=="unBlocked" %}
                        <a href="{{ path('app_user_block',{'id':user.id}) }}"><img src="{{ asset('unlocked.png') }}" width="30" height="30"></a>
                    {% else %}
                        <a href="{{ path('app_user_unblock',{'id':user.id}) }}"><img src="{{ asset('lock.png') }}" width="30" height="30"></a>
                    {% endif %}
                </td>
            </tr>

        {% else %}
            <tr>
                <td colspan="11">Aucun utilisateur</td>
            </tr>

        {% endfor %}
        </tbody>
    </table>
                <button class="btn btn-primary" onclick="window.location.href='{{ path('app_user_new2' ) }}'">Créer un utilisateur</button>
                <button class="btn btn-primary" onclick="window.location.href='{{ path('app_user_stats' ) }}'">Stats</button><!--BOUTON STAT-->
                <div class="text-center">

                    {{ knp_pagination_render(users) }}

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block footer %}
    <!-- Create a div element for the map -->
    <div id="mapid" style="height: 600px;"></div>
    <!-- Include Leaflet JS -->
    <!--BIBLIOTHEQUE javascript leaflet-->
    <script src="https://cdn.jsdelivr.net/npm/leaflet@1.7.1/dist/leaflet.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", function(event) {
            var map = L.map('mapid').setView([34.0, 9.0], 7);

            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: 'Map data © <a href="https://openstreetmap.org">OpenStreetMap</a> contributors',
                minZoom: 1,
                maxZoom: 20
            }).addTo(map);

            var markers = {{ markers|json_encode()|raw }};
            console.log(markers);
            var userbyadress= {{ userbyadress|json_encode()|raw }};

            for (var i = 0; i < markers.length; i++) {
                var marker = L.marker([markers[i].lat, markers[i].lng]).addTo(map);
                var popupContent = markers[i].popupContent;
                var nbusers = userbyadress[popupContent] ?? 0;
                popupContent += "<br>" + nbusers + " Users";
                marker.bindPopup(popupContent);
            }
        });

    </script>

{% endblock %}

templates/user/new.html.twig
{% extends 'auth-signup-cover.html.twig' %}

    {% block register %}

        {{ include('user/_form.html.twig') }}


{% endblock %}

templates/user/new2.html.twig
{% extends 'baseBack.html.twig' %}

{% block tableForm %}


    {{ include('user/_formnew2.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_user_index') }}">Retour</a>

{% endblock %}

templates/user/role_chart.html.twig
{% extends 'baseBack.html.twig' %}

{% block stats %}
<section class="section"> <!--dans la baseback.html.twig j'ai un block de statistique line 356-->
    <div class="row">
        <div class="col-lg-6" >
            <div class="card" >

                    <div class="card-body">
                        <h5 class="card-title">Distribution des utilisateurs par role</h5>

                        <!-- Pie Chart -->
                        <div id="role_chart"></div>
                        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script><!--j'ai utiliser bib loader.js pour loader la charte-->
                        <script type="text/javascript">
                            {{ gc_draw(chart2, 'role_chart') }}//le chart que j'ai envoyer apartir de controlleur 'chart2' ligne 455 je le fait lappelle apArtir gc_draw
                        </script>
                    </div>

            </div>
        </div>
        </div>
        </div>
    </div>
    </div>
</section>
{% endblock %}

templates/user/show.html.twig
{% extends 'baseBack.html.twig' %}

{% block tableForm %}
<div style=" justify-content: center; margin-left: 150px;">

    <div class="card">
        <div  style="display: flex;align-items: center;justify-content: center;margin-top: 20px; padding: 50px;">

            <div class="card-body">
                <center> <h1 class="card-title" >Profil utilisateurs</h1> </center>



                <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                {% if "ROLE_CLIENT" in user.roles %}
                <td>Client</td>
                {% else %}
                <td>Freelancer</td>
                {% endif %}
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ user.prenom }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ user.nom }}</td>
            </tr>
            <tr>
                <th>Date_naissance</th>
                <td>{{ user.dateNaissance ? user.dateNaissance|date('Y-m-d') : '' }}</td>
            </tr>

            <tr>
                <th>NumTel</th>
                <td>{{ user.numTel }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ user.adresse }}</td>
            </tr>
        </tbody>
    </table>
                <button class="btn btn-primary" onclick="window.location.href='{{ path('app_user_index' ) }}'">Retour</button>

                <button class="btn btn-primary" onclick="window.location.href='{{ path('app_user_edit',{'id':user.id} ) }}'">Modifier</button>
                {{ include('user/_delete_form.html.twig') }}
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/user/showAdmin.html.twig
{% extends 'baseBack.html.twig' %}

{% block tableForm %}
<div style=" justify-content: center; margin-left: 150px;">

    <div class="card">
        <div  style="display: flex;align-items: center;justify-content: center;margin-top: 20px; padding: 50px;">

            <div class="card-body">
                <center> <h1 class="card-title" >Mon profil</h1> </center>



                <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ user.prenom }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ user.nom }}</td>
            </tr>
            <tr>
                <th>Date_naissance</th>
                <td>{{ user.dateNaissance ? user.dateNaissance|date('Y-m-d') : '' }}</td>
            </tr>

            <tr>
                <th>NumTel</th>
                <td>{{ user.numTel }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ user.adresse }}</td>
            </tr>
        </tbody>
    </table>
                <button class="btn btn-primary" onclick="window.location.href='{{ path('app_user_index' ) }}'">Retour</button>

                <button class="btn btn-primary" onclick="window.location.href='{{ path('app_user_editadmin',{'id':user.id} ) }}'">Modifier</button>
                {{ include('user/_delete_form.html.twig') }}
            </div>
        </div>
    </div>
</div>


{% endblock %}